<a href="https://colab.research.google.com/github/migot01/Linear-Regression-with-sklearn/blob/master/multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
sns.set()

from sklearn.linear_model import LinearRegression

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [0]:
#this loads the spreadsheet from google drive
from google.colab import auth
auth.authenticate_user()

import gspread
from oauth2client.client import GoogleCredentials


from IPython.display import display
gc = gspread.authorize(GoogleCredentials.get_application_default())
worksheet = gc.open('test_data2')
sheet = worksheet.sheet1 #choose the first sheet
import pandas
data = pandas.DataFrame(sheet.get_all_records())

In [0]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [0]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [0]:
## Create multilinear regression

# Declare the dependent and independent variables
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']


In [0]:
# Regression itself

reg = LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [0]:
reg.intercept_

0.29603261264909486

In [0]:
#Calculating R-squared
reg.score(x,y)

0.4066811952814285

$R^2_(adj.) = 1 - (1-R^2)*\frac(n-1)(n-p-1)$

In [0]:
x.shape

(84, 2)



1.   n = 84 (the number of observations)
2.   p = 2 (the number of predictors)







In [0]:
r2 = reg.score(x,y)

n = x.shape[0]
p = x.shape[1]
adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2


0.39203134825134023

## **Feature Selection**

In [0]:
from sklearn.feature_selection import f_regression
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [0]:
p_values = f_regression(x,y)[1]

In [0]:
p_values

array([7.19951844e-11, 6.76291372e-01])

In [0]:
p_values.round(3)

array([0.   , 0.676])

# Standardization

In [0]:
from sklearn.preprocessing import StandardScaler


In [0]:
scaler = StandardScaler()

In [0]:
scaler.fit(x,y)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [0]:
x_scaled = scaler.transform(x)

In [0]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,